
cronSchedule: "0 8 * * 0"

image:
  repository: "zufardhiyaulhaq/javascriptweekly"
  tag: "v1.1.0"

secret: ""

weekly:
  community: "JavaScript Indonesia Community"
  tags: "weekly,nodejs"
  namespace: "javascript-community"
  image_url: "https://www.purelogics.net/blog/wp-content/uploads/2019/01/javascript.png"

